#!/bin/bash

source /bin/update-common.sh

wait () {
    while [ "$(lsof -w -- /var/run/update-ipsets.lock)" ];
    do
        echo "waiting for update-ipsets to finish..."
        sleep 1
    done
}

wait
update-ipsets enable $1 2>&1
touch /etc/firehol/ipsets/$1.enabled

has_dep=true
while $has_dep;
do
    has_dep=false
    wait
    out=`update-ipsets -s 2>&1 | grep "will be generated without"`
    while read i;
    do
        f=`echo $i | awk -F "[']" '{ print $2 }'`
        if [[ ! -z $f ]];
        then
            should_skip "$f"
            if [ $? == 1 ]; then
                continue
            fi
            has_dep=true
            wait
            echo "Enabling set $f which depends on $1"
            update-ipsets enable $f 2>&1
            sf=`echo $f | sed -E 's/_[0-9]+d//g'`
            if [ $f != $sf ];
            then
                should_skip "$f"
                if [ $? == 1 ]; then
                    continue
                fi
                wait
                update-ipsets enable $sf 2>&1
            fi
        fi
    done <<< "$out"
done

ipset-apply $1

add_rule_for_set $1
