#!/bin/bash

wait () {
    while [ "$(lsof -w -- /var/run/update-ipsets.lock)" ];
    do
        echo "waiting for update-ipsets to finish..."
        sleep 1
    done
}

wait
update-ipsets enable $1 2>&1
update-ipsets -s 2>&1

ipset-apply $1
ipset save | grep create > /etc/firehol/ipsets/ipset-names.latest # save the latest ipsets (names only)

if [[ -z `iptables -L INPUT | grep "match-set $1 src"` ]];
then
    iptables -I INPUT -m set --match-set $1 src -j DROP
fi
if [[ -z `iptables -L DOCKER-USER | grep "match-set $1 src"` ]];
then
    iptables -I DOCKER-USER -m set --match-set $1 src -j DROP
fi
