#!/bin/bash

# better to update the update-ipsets script to the newest version (IP list providers are updated daily basis)
curl -L https://raw.githubusercontent.com/firehol/firehol/master/sbin/update-ipsets -o /sbin/update-ipsets && chmod a+x /sbin/update-ipsets

# restore the latest ipsets
if [ -e /etc/firehol/ipsets/ipset-names.latest ];
then
    ipset restore < /etc/firehol/ipsets/ipset-names.latest
fi

iptables -n --list FIREHOL_BLACKLIST >/dev/null 2>&1
if [ $? == 1 ]; then
  iptables -N FIREHOL_BLACKLIST
  iptables -A INPUT -j FIREHOL_BLACKLIST
  iptables -A DOCKER-USER -j FIREHOL_BLACKLIST
fi

for i in $(find /etc/firehol/ipsets -maxdepth 1 -name "*.enabled");
do
    i="${i##*/}"
    i="${i%.*}"
    ipset-apply $i
    if [[ -z $(iptables -L FIREHOL_BLACKLIST | grep "match-set $i src") ]];
    then
        iptables -I FIREHOL_BLACKLIST -m set --match-set $i src -j DROP
    fi
done

while :
do
    update-ipsets -s
    sleep $((($RANDOM % 20 + 50) * 10)) # sleeps for about 10 minutes (add random variable to avoid DDoS to iplist provider)
done
